name: api-import


on:
  workflow_dispatch:

jobs:
  create-org-data:
    runs-on: ubuntu-latest
    steps:
      - name: Generate list of potential projects to import
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            /bin/bash scripts/install_snyk_tools.sh
            .bin/snyk-api-import import:data --orgsData=org-data.json --source=github --integrationType=github-enterprise
          COMMIT_MESSAGE: 'chore: Update Orgs to Import'
          COMMIT_NAME: 'GitHub Actions'
          COMMIT_EMAIL: 'example@example.com'
          PR_BRANCH_NAME: 'chore-api-import-update-${PR_ID}'
          PR_TITLE: 'chore: update org list'
        env:
          SNYK_LOG_PATH: 'org_data'
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}